import type { Product } from "@prisma/client";
import { PackageOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DeleteProductButton } from "./delete-product-button";
import { ProductDialog } from "./product-dialog";

export function ProductTable({ products }: { products: Product[] }) {
  if (products.length === 0) return <div className="flex min-h-72 flex-col items-center justify-center rounded-lg border border-dashed border-slate-300 bg-white text-center"><PackageOpen size={38} className="mb-3 text-slate-300" /><p className="font-semibold text-slate-700">조건에 맞는 제품이 없습니다.</p><p className="mt-1 text-sm text-slate-500">검색 조건을 바꾸거나 새 제품을 등록해 주세요.</p></div>;
  return <div className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr>{["번호","품목코드","품목명","카테고리","판매단위","사용 여부","등록일","관리"].map((header) => <th key={header} className="border-b border-slate-200 px-5 py-3.5">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{products.map((product, index) => <tr key={product.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 text-slate-500">{index + 1}</td><td className="px-5 py-4 font-mono text-xs font-semibold text-slate-700">{product.code}</td><td className="px-5 py-4 font-semibold text-slate-900">{product.name}</td><td className="px-5 py-4 text-slate-600">{product.category}</td><td className="px-5 py-4 text-slate-600">{product.unit}</td><td className="px-5 py-4"><span className={product.isActive ? "rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700" : "rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500"}>{product.isActive ? "사용" : "미사용"}</span></td><td className="px-5 py-4 whitespace-nowrap text-slate-600">{new Intl.DateTimeFormat("ko-KR").format(product.createdAt)}</td><td className="px-5 py-4"><div className="flex"><ProductDialog product={product} trigger={<Button size="sm" variant="ghost">수정</Button>} /><DeleteProductButton id={product.id} name={product.name} /></div></td></tr>)}</tbody></table></div></div>;
}
