"use client";

import { AlertTriangle, CircleCheck } from "lucide-react";
import { MARKETPLACE_LABELS } from "@/lib/shipping/marketplace-detector";
import type { ConvertedShippingRow } from "@/lib/shipping/types";

export function ShippingPreviewTable({ orders }: { orders: ConvertedShippingRow[] }) {
  if (!orders.length) return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">엑셀을 업로드하면 변환 결과가 여기에 표시됩니다.</div>;
  const headers = ["번호", "판매처", "원본 행", "수화인명", "우편번호", "주소", "전화번호", "휴대폰번호", "택배수량", "물품명", "배송메세지", "택배운임타입", "상태"];
  return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1400px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-600"><tr>{headers.map((header) => <th key={header} className="whitespace-nowrap border-b border-slate-200 px-3 py-3">{header}</th>)}</tr></thead><tbody>{orders.map((order, index) => { const missing = order.validation.missingFields; const review = !order.validation.isValid; return <tr key={`${order.source}-${order.sourceFileName}-${order.sourceRowNumber}`} className="border-b border-slate-100 last:border-0"><td className="px-3 py-3 text-slate-500">{index + 1}</td><td className="whitespace-nowrap px-3 py-3"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{MARKETPLACE_LABELS[order.source]}</span></td><td className="px-3 py-3" title={order.sourceFileName}>{order.sourceRowNumber}</td><td className="px-3 py-3">{order.receiverName}</td><td className="px-3 py-3">{order.postalCode}</td><td className="max-w-72 px-3 py-3">{order.address}</td><td className="px-3 py-3">{order.phone}</td><td className="px-3 py-3">{order.mobilePhone}</td><td className="px-3 py-3">{order.packageQuantity}</td><td className="max-w-72 px-3 py-3">{order.productName}</td><td className="max-w-64 px-3 py-3">{order.deliveryMessage}</td><td className="px-3 py-3">{order.shippingFareType}</td><td className="px-3 py-3"><span className={review ? "inline-flex items-center gap-1 whitespace-nowrap rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700" : "inline-flex items-center gap-1 whitespace-nowrap rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700"}>{review ? <AlertTriangle size={13} /> : <CircleCheck size={13} />}{review ? `확인 필요: ${missing.join(", ")} 없음` : "정상"}</span></td></tr>; })}</tbody></table></div></div>;
}
